# Generated by Django 4.1.7 on 2023-06-07 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('doc_identidad', models.TextField(max_length=11, unique=True)),
                ('celular', models.TextField(max_length=11)),
                ('codigo_estudiantil', models.TextField(max_length=11, unique=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programa_acompañamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(choices=[('Psicología', 'Psicología'), ('Red CAAL', 'Red CAAL')], max_length=20, unique=True)),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripción del programa')),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dexia_estudiantes.estudiante')),
                ('pograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_dexia_estudiantes.programa_acompañamiento')),
            ],
        ),
    ]
